version: "3.1"

services:
  scheduler:
    build:
      # context: ../base
      context: .
      dockerfile: Dockerfile
      args:
        release: "2022.10.1"
    # image: ghcr.io/dask/dask:latest
    image: asia.gcr.io/retailigence-2020/dev-daskgateway:2.786
    hostname: dask-scheduler
    ports:
      - "8786:8786"
      - "8787:8787"
    command: ["dask-scheduler"]

  worker:
    build:
      # context: ../base
      context: .
      dockerfile: Dockerfile
      args:
        python: "3.8"
        release: "2022.10.1"
    # image: ghcr.io/dask/dask:latest
    image: asia.gcr.io/retailigence-2020/dev-daskgateway:2.786
    hostname: dask-worker
    command: ["dask-worker", "tcp://scheduler:8786"]
