version: "3.1"

services:
  scheduler:
    build:
      context: ../base
      dockerfile: Dockerfile
      args:
        release: "2022.12.1"
    image: ghcr.io/dask/dask:latest
    hostname: dask-scheduler
    ports:
      - "8786:8786"
      - "8787:8787"
    command: ["dask-scheduler"]

  worker:
    build:
      context: ../base
      dockerfile: Dockerfile
      args:
        python: "3.8"
        release: "2022.12.1"
    image: ghcr.io/dask/dask:latest
    hostname: dask-worker
    command: ["dask-worker", "tcp://scheduler:8786"]
