version: "3.1"

services:
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        release: "2022.12.1"
    image: asia.gcr.io/retailigence-2020/dev-daskgateway:2.771
    hostname: dask-scheduler
    ports:
      - "8786:8786"
      - "8787:8787"
    command: ["dask-scheduler"]

  docker-stacks-foundation:
    build:
      context: github.com/jupyter/docker-stacks.git#main:docker-stacks-foundation
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: "3.8"
    image: asia.gcr.io/retailigence-2020/dev-daskgateway:2.771

  worker:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        python: "3.8"
        release: "2022.12.1"
    image: asia.gcr.io/retailigence-2020/dev-daskgateway:2.771
    hostname: dask-worker
    command: ["dask-worker", "tcp://scheduler:8786"]

  notebook:
    build:
      context: ../notebook
      dockerfile: Dockerfile
      args:
        base: daskdev
        python: "3.8"
        release: "2022.12.1"
    depends_on:
      - docker-stacks-foundation
    image: asia.gcr.io/retailigence-2020/dev-daskgateway:2.771
    hostname: notebook
    ports:
      - "8888:8888"
    environment:
      - DASK_SCHEDULER_ADDRESS="tcp://scheduler:8786"