version: "3.1"

services:
  scheduler:
    # image: ghcr.io/dask/dask:latest
    image: asia.gcr.io/retailigence-2020/dev-daskgateway:2.769
    hostname: scheduler
    ports:
      - "8786:8786"
      - "8787:8787"
    command: ["dask-scheduler"]

  worker:
    # image: ghcr.io/dask/dask:latest
    image: asia.gcr.io/retailigence-2020/dev-daskgateway:2.771
    command: ["dask-worker", "tcp://scheduler:8786"]
    # For Docker swarm you can specify multiple workers, this is ignored by `docker-compose up`
    deploy:
      replicas: 2

  notebook:
    # image: ghcr.io/dask/dask-notebook:latest
    image: asia.gcr.io/retailigence-2020/dev-daskgateway:2.771
    ports:
      - "8888:8888"
    environment:
      - DASK_SCHEDULER_ADDRESS="tcp://scheduler:8786"